# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 20:36
from __future__ import unicode_literals

import ShelfiePost.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ShelfieGame', '0001_initial'),
        ('ShelfieChallenge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('random_post_id', models.CharField(default=ShelfiePost.models.random_id, editable=False, max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='Random Post Id')),
                ('media_url', models.CharField(blank=True, max_length=120, null=True)),
                ('caption', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShelfieChallenge.Challenge')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShelfieGame.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
