# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfiePost', '0003_auto_20180204_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
