# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 19:02
from __future__ import unicode_literals

import ShelfiePost.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShelfiePost', '0006_auto_20180215_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('random_report_id', models.CharField(default=ShelfiePost.models.random_id, editable=False, max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='Random Report Id')),
                ('message', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShelfiePost.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
