# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 06:35
from __future__ import unicode_literals

import ShelfieNotification.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('random_notification_id', models.CharField(default=ShelfieNotification.models.random_id, editable=False, max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='Random Notification Id')),
                ('category', models.CharField(choices=[('like', 'Like'), ('follow', 'Follow'), ('prize', 'Prize')], max_length=120)),
                ('message', models.CharField(blank=True, max_length=120, null=True)),
                ('active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
