# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfiePost', '0006_auto_20180215_0544'),
        ('ShelfieNotification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShelfiePost.Post'),
        ),
    ]
