# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 19:57
from __future__ import unicode_literals

import ShelfieChallenge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('random_challenge_id', models.CharField(default=ShelfieChallenge.models.random_id, editable=False, max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='Random Challenge Id')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('point_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
