# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieChallenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.CharField(default='Description', max_length=120),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(default='Name', max_length=120),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='point_value',
            field=models.IntegerField(default=0),
        ),
    ]
