# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieChallenge', '0003_auto_20180215_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to='challenges'),
        ),
    ]
