# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieChallenge', '0004_challenge_background_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='background_photo',
            field=models.ImageField(default='https://shelfie-challenge', upload_to='challenges'),
        ),
    ]
