# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 08:10
from __future__ import unicode_literals

import ShelfieGame.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ShelfieChallenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('random_game_id', models.CharField(default=ShelfieGame.models.random_id, editable=False, max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='Random Game Id')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('team_1', models.CharField(blank=True, max_length=120, null=True)),
                ('team_2', models.CharField(blank=True, max_length=120, null=True)),
                ('home_team', models.CharField(blank=True, max_length=120, null=True)),
                ('organization', models.CharField(blank=True, max_length=120, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShelfieChallenge.Challenge')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShelfieGame.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='challenges',
            field=models.ManyToManyField(through='ShelfieGame.GameChallenge', to='ShelfieChallenge.Challenge'),
        ),
    ]
