# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 08:23
from __future__ import unicode_literals

import ShelfieGame.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieGame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamechallenge',
            name='id',
        ),
        migrations.AddField(
            model_name='gamechallenge',
            name='game_challenge_id',
            field=models.CharField(default=ShelfieGame.models.random_id, editable=False, max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='Game Challenge Id'),
        ),
    ]
