# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfiePrize', '0001_initial'),
        ('ShelfieGame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='prizes',
            field=models.ManyToManyField(to='ShelfiePrize.Prize'),
        ),
    ]
