# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieGame', '0002_game_prizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='prizes',
            field=models.ManyToManyField(blank=True, to='ShelfiePrize.Prize'),
        ),
    ]
