# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieGame', '0009_auto_20180209_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='organization',
        ),
    ]
