# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieTeam', '0003_auto_20180209_2128'),
        ('ShelfieGame', '0010_auto_20180209_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='ShelfieTeam.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='ShelfieTeam.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='ShelfieTeam.Team'),
        ),
    ]
