# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieGame', '0011_auto_20180209_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default='2018-02-16 18:00:00'),
        ),
    ]
