# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfiePrize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='description',
            field=models.CharField(default='description', max_length=120),
        ),
        migrations.AlterField(
            model_name='prize',
            name='name',
            field=models.CharField(default='name', max_length=120),
        ),
        migrations.AlterField(
            model_name='prize',
            name='winner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
