# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfiePrize', '0004_prize_background_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='background_photo',
            field=models.ImageField(default='challenges/laurel-wreath-304839_1280withbackground.png', upload_to='challenges'),
        ),
    ]
