# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-03 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfiePrize', '0005_auto_20180302_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='background_photo',
            field=models.ImageField(default='prizes/laurel-wreath-304839_1280withbackground.png', upload_to='prizes'),
        ),
    ]
