# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfiePrize', '0006_auto_20180303_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='background_photo',
            field=models.ImageField(default='prizes/shelfie_prize_background.png', upload_to='prizes'),
        ),
    ]
