# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 04:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfiePrize', '0007_auto_20180313_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
