# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieKey', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AWS',
            new_name='AmazonS3',
        ),
    ]
