# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieUser', '0005_auto_20180217_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='https://shelfie-challenge-staging.s3.amazonaws.com/users%2Fprofile-photos%2Fdefault_profile.png', max_length=120),
        ),
    ]
