# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-16 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieUser', '0007_auto_20180313_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
