# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieUser', '0008_user_reset_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_team',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Favorite Team'),
        ),
    ]
