# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 21:13
from __future__ import unicode_literals

import ShelfieTeam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('random_team_id', models.CharField(default=ShelfieTeam.models.random_id, editable=False, max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='Random Team Id')),
                ('name', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=120, null=True)),
                ('point_of_contact', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
