# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieTeam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Team',
        ),
    ]
