# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieTeam', '0002_auto_20180209_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
