# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieTeam', '0004_auto_20180209_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='name', max_length=120),
        ),
    ]
