# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfieTeam', '0006_auto_20180215_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='teams/logos'),
        ),
    ]
